language: go
sudo: false

go:
- 1.1.2
- 1.2.2
- 1.3.3
- 1.4.2
- 1.5.1
- tip

matrix:
  allow_failures:
    - go: 1.1.2

install:
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify/assert

before_script:
  - go vet ./...

script:
  - make
  - make test-cover-builder
  - $HOME/gopath/bin/goveralls -coverprofile=/tmp/art_coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
